weather_in_country_and_city:
    path: /weather/{country}/{city}
    controller: App\Controller\WeatherController:cityAndCountryAction
weather_in_city:
    path: /weather/{city}
    controller: App\Controller\WeatherController:cityAction
    requirements:
        city: \d+
app_logout:
    path: /logout
    methods: GET
